### ISSUE TITLE
problem with you implementation of ic2 inheritance storage mecanism

### ISSUE THREAD

**Issue by changemenemo** [CyclopsMC/EnergySynergy#10]
Hi,

as indicated [here](https://forum.industrial-craft.net/thread/14844-crash-client-problem-with-mfe-mfsu-and-batbox/#post210017) which points to [here](https://github.com/CyclopsMC/EnergySynergy/blob/0a54db8b71d79f526d55928f9f98ae72ca2cf398/src/main/java/org/cyclops/energysynergy/modcompat/ic2/capability/tesla/Ic2TeslaIntegration.java#L71-L72) I think,
you presume something worng about IC2 which cause me headache today when I try to put my server up to date with your mods. I have a lot of error all over the place because MFE, MFSU and batbox are not implemented correctly in your mod. And So if I try to place a new one, it crashs my game completely.
It was not happening with your old version 1.1.1 and cyclopscore 0.10.0 . 
So please can you make us an hotfix for the 1.10.2 minecraft version at least? I can't work without my tools:( 
best regards

**Comment by rubensworks** [comment]
That's a bug indeed. I fixed this in the 1.12 version, but I forgot to backport it to the earlier versions apparently.

**Comment by changemenemo** [comment]
great if you already know what to change then :) , I hope I will be able to activate my server soon again :)

**Comment by rubensworks** [comment]
For now, you can disable IC2/FE integration from the config file.

**Comment by changemenemo** [comment]
ow I didn't see that there was a config file for that, let me check.

**Comment by changemenemo** [comment]
ok caught it. I will check with the others if it s okey after that
