### ISSUE TITLE
EU to RF conversion is missing

### ISSUE THREAD

**Issue by iridiumlynx** [CyclopsMC/EnergySynergy#14]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. Install IC2, ThermalExpansion, EnergySynergy and their dependencies.
2. Connect a machine from Thermal Expansion to MFE/MFSU/BatBox or any generator from IC2.

#### Expected behaviour:

An IC2 generator or IC2 energy storage must transfer energy to machines from Thermal Expansion, but it doesn't.
____

#### Versions:

- This mod: 1.1.3
- IC2: 2.8.81
- Thermal Expansion: 5.5.0.29
- Redstone Flux: 2.0.2.3
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

**Comment by rubensworks** [comment]
This is not a bug, only the other way around works.

From the mod description:

> This mod allows you to automatically convert Tesla and Forge energy to RF and EU, in both machines and items.

> Note that the other way around (RF or EU to Tesla or Forge) is not supported, this would require too much intrusive hacks.
