### ISSUE TITLE
Energy Item compatibility

### ISSUE THREAD

**Issue by iridiumlynx** [CyclopsMC/EnergySynergy#15]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Please add ability to charge energy items from different mods with any supported energy type.

**Comment by rubensworks** [comment]
Your request is very vague...

This mod does not do charging, it only does conversion of energy.

_any_ energy type is not possible, support has to be added manually. Please do separate requests for each of them.
