### ISSUE TITLE
EU-Storages do not fill to more than 2147483647 EU with power from non-EU sources

### ISSUE THREAD

**Issue by glowredman** [CyclopsMC/EnergySynergy#16]
#### Issue type:

- :bug: Bug

____

#### Short description:

Some IC2 addons add storage block which can hold more than `Integer.MAX_VALUE` EU. In this case, the blocks will fill up only to that limit, when powered with a non-EU source.

#### Steps to reproduce the problem:

1. Install EnergySynergy, IC2, Thermal Expansion and WTF Ic2 Addon
2. Place an Energy Cell and upgrade it to creative
3. Place a Double Compressed MFSU (or higher) next to it (pay attention to inputs/outputs!)
4. Observe the energy amount in the MFSU

#### Expected behaviour:

The MFSU should keep charging.

____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- IC2: 2.8.170

**Comment by rubensworks** [comment]
Thanks for reporting!

Not sure this can be fixed though, as this could be a fundamental limitation of the API.
