### ISSUE TITLE
continus #8 (Molecular Transformer)

### ISSUE THREAD

**Issue by ptk2003** [CyclopsMC/EnergySynergy#9]
After update still not working.
And can not extract RF from quantum solar panel. The one probe says about "0 RF" contain in battery, but it charged.

forge-1.10.2-12.18.3.2281-universal
CyclopsCore-1.9.4-0.10.5
EnergySynergy-1.10.2-1.1.2
industrialcraft-2-2.6.232-ex110
Advanced Solar Panels 4.0.4

**Comment by rubensworks** [comment]
I tried the molecular transformer myself, and it seems to work just fine.
Are you sure you are providing a valid input item? Otherwise it won't accept energy.

I'm not sure if the solar panels will ever work, as I think they push energy themself. I'll have to look into it.

**Comment by ptk2003** [comment]
just maybe i do something wrong :)
i update enderio and cofh, remove others and now
MT accept rf energy from capacitor/cell/conduit
but energy cell not discharging :D
replace MT other rf machine discharge battery as usual.

cryoflux pipe not connecting to solar panel
enderio conduit connecting, but both not extract energy
http://i.imgur.com/PdSLrEy.png
http://i.imgur.com/uPZShiL.png
http://i.imgur.com/Zl6qYKX.png

placed solar panel directry capacitor bank same result
http://i.imgur.com/X3XEiwD.png

MT working from capacitor, but not discharging
(capacitor not creative)
http://i.imgur.com/hX5eQ6M.png
http://i.imgur.com/TvzXKKI.png

**Comment by rubensworks** [comment]
The latest dev build fixes the issue.
Note that the solar panel (or any other IC2-based machine) will be able to output energy itself as FE/RF/Tesla. You will have to extract the energy yourself from the machine due to the way capability-injection works (which this mod is based on).
